[workspace]
members = [
	"docbrown/core",
	"docbrown/db",
	"examples/rust",
	"pyraphtory"
]
default-members = ["docbrown/core", "docbrown/db", "pyraphtory"]

[workspace.package]
version = "0.0.2"
documentation = "https://docbrown.readthedocs.io/en/latest/"
repository = "https://github.com/Raphtory/docbrown/"
license = "AGPL-3.0-only"
readme = "README.md"
homepage = "https://github.com/Raphtory/docbrown/"
keywords = ["graph", "temporal-graph", "temporal"]
authors = ["Pometry"]
rust-version = "1.67.1"
edition = "2021"
