[workspace]
members = [
	"algorithms",
	"docbrown/core",
	"docbrown/db",
	"examples/rust",
	"pyraphtory"
]
default-members = ["docbrown/core", "docbrown/db", "pyraphtory"]

[workspace.package]
version = "0.1.0"
