[workspace]
members = [
	"docbrown/core",
	"docbrown/db",
	"examples",
	"docbrown/pyraphtory"
]
default-members = ["docbrown/core", "docbrown/db", "docbrown/pyraphtory"]

[workspace.package]
version = "0.1.0"
