[workspace]
members = [
	"docbrown/core",
	"docbrown/db",
	"docbrown/algorithms",
	"examples"
]
default-members = ["docbrown/core", "docbrown/db","docbrown/algorithms"]

[workspace.package]
version = "0.1.0"
