on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: actions-rs/toolchain@v1
        name: Setup Rust
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/debug
            target/release
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Build project quietly
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -q
      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Restore benchmark results from main
        uses: actions/cache/restore@v3
        id: restore-cache
        with:
          path: target/criterion
          key: ${{ runner.os }}-criterion
      - name: Run benchmark
        run: cargo bench --bench base | tee benchmark-result.txt
      - name: Fail on performance regresion
        run: ! cat benchmark-result.txt | grep "Performance has regressed" > /dev/null
      - name: Save benchmark results from main
        uses: actions/cache/save@v3
        if: github.ref == 'refs/heads/main'
        with:
          path: target/criterion
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}
