name: Publish Rust/PyRaphtory to Github, crates.io and PyPi
on:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release code
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0