name: Publish a new Release
on:
  workflow_dispatch:
    inputs:
      base:
        description: 'Name of branch to open PR against'
        type: 'string'
        default: 'main'
      version:
        description: 'Version to bump to (e.g. 0.1.0)'
        type: 'string'
        required: true

jobs:
  test-rust-python-workflow:
    uses: ./.github/workflows/test_rust_workflow.yml
    secrets: inherit
  publish-builds-to-cargo-github-pypi:
    needs: test-rust-python-workflow
    uses: ./.github/workflows/publish_builds.yml
    secrets: inherit
    with:
        version: ${{ github.event.inputs.version }}
        base: ${{ github.event.inputs.base }}
