name: Publish a new Release
on:
  push:
    tags:
      - 'v*'

jobs:
  test-rust-python-workflow:
    uses: ./.github/workflows/test_rust_workflow.yml
    secrets: inherit
  publish-builds-to-cargo-github-pypi:
    needs: test-scala-python-workflow
    uses: ./.github/workflows/publish_builds.yml
    secrets: inherit
